# Generated by Django 5.0.2 on 2024-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bill_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
