# Generated by Django 5.0.2 on 2024-03-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
